runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:zSumHmqZU2qp8Mzob5OtuF7n9/tgxFNxNfxNAd7FlbM=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_DATABASE: socialdb
  DB_USERNAME: root
  DB_PASSWORD: root
  ## for MYSQL, use DB_SOCKET:
  DB_SOCKET: "/cloudsql/social-278718:us-central1:socialdb"